foq_album_index:
    pattern:    /
    defaults:   { _controller: foq_album.controller.album:indexAction }
    requirements: { _method: "get|head" }

foq_album_album_new:
    pattern:    /-/add
    defaults:   { _controller: foq_album.controller.album:newAction }
    requirements: { _method: "get|head|post" }

foq_album_album_edit:
    pattern:    /-/edit/{username}/{slug}
    defaults:   { _controller: foq_album.controller.album:editAction }
    requirements: { _method: "get|head|post" }

foq_album_album_upload:
    pattern:    /-/upload/{username}/{slug}
    defaults:   { _controller: foq_album.controller.album:uploadAction }
    requirements: { _method: "get|head|post" }

foq_album_album_upload_callback:
    pattern:    /-/upload-callback/{username}/{slug}
    defaults:   { _controller: foq_album.controller.album:uploadCallbackAction }
    requirements: { _method: "get|head|post" }

foq_album_album_delete:
    pattern:  /-/delete/{username}/{slug}
    defaults:  { _controller: foq_album.controller.album:deleteAction }

foq_album_album_publish:
    pattern:  /-/publish/{username}/{slug}
    defaults:  { _controller: foq_album.controller.album:publishAction }

foq_album_album_by_user:
    pattern:    /{username}
    defaults:   { _controller: foq_album.controller.album:listByUserAction }
    requirements: { _method: "get|head" }

foq_album_album_show:
    pattern:    /{username}/{slug}
    defaults:   { _controller: foq_album.controller.album:showAction }
    requirements: { _method: "get|head", slug: "[\w\d-]+" }

foq_album_photo_show:
    pattern: /{username}/{slug}/{number}
    defaults: { _controller: foq_album.controller.photo:showAction }
    requirements: { _method: "get|head", slug: "[\w-]+", number: "\d+" }

foq_album_photo_delete:
    pattern: /-/delete/{username}/{slug}/{number}
    defaults: { _controller: foq_album.controller.photo:deleteAction }
    requirements: { _method: "get|head", slug: "[\w-]+", number: "\d+" }